# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HH_dist <- function(beta, param, grid_a, grid_a_NS, grid_z, prob_z, wToday, RToday, tauToday, dToday, pf_c, pf_n, pf_sav) {
    .Call(`_MNS2016_HH_dist`, beta, param, grid_a, grid_a_NS, grid_z, prob_z, wToday, RToday, tauToday, dToday, pf_c, pf_n, pf_sav)
}

HH_opt_EGM <- function(beta, param, grid_a, grid_z, prob_z, wToday, RToday, tauToday, dToday, pf_c_init, pf_n_init, pf_sav_init) {
    .Call(`_MNS2016_HH_opt_EGM`, beta, param, grid_a, grid_z, prob_z, wToday, RToday, tauToday, dToday, pf_c_init, pf_n_init, pf_sav_init)
}

pchip <- function(knot_x, knot_y, x) {
    .Call(`_MNS2016_pchip`, knot_x, knot_y, x)
}

