// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// HH_dist
List HH_dist(double beta, List param, NumericVector grid_a, NumericVector grid_a_NS, NumericVector grid_z, NumericMatrix prob_z, double wToday, double RToday, double tauToday, double dToday, NumericMatrix pf_c, NumericMatrix pf_n, NumericMatrix pf_sav);
RcppExport SEXP _MNS2016_HH_dist(SEXP betaSEXP, SEXP paramSEXP, SEXP grid_aSEXP, SEXP grid_a_NSSEXP, SEXP grid_zSEXP, SEXP prob_zSEXP, SEXP wTodaySEXP, SEXP RTodaySEXP, SEXP tauTodaySEXP, SEXP dTodaySEXP, SEXP pf_cSEXP, SEXP pf_nSEXP, SEXP pf_savSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_a(grid_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_a_NS(grid_a_NSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_z(grid_zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prob_z(prob_zSEXP);
    Rcpp::traits::input_parameter< double >::type wToday(wTodaySEXP);
    Rcpp::traits::input_parameter< double >::type RToday(RTodaySEXP);
    Rcpp::traits::input_parameter< double >::type tauToday(tauTodaySEXP);
    Rcpp::traits::input_parameter< double >::type dToday(dTodaySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf_c(pf_cSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf_n(pf_nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf_sav(pf_savSEXP);
    rcpp_result_gen = Rcpp::wrap(HH_dist(beta, param, grid_a, grid_a_NS, grid_z, prob_z, wToday, RToday, tauToday, dToday, pf_c, pf_n, pf_sav));
    return rcpp_result_gen;
END_RCPP
}
// EGMconstrained
List EGMconstrained(List param, double aToday, double zToday, double RToday, double wToday, double tauToday, double dToday, int i_z);
RcppExport SEXP _MNS2016_EGMconstrained(SEXP paramSEXP, SEXP aTodaySEXP, SEXP zTodaySEXP, SEXP RTodaySEXP, SEXP wTodaySEXP, SEXP tauTodaySEXP, SEXP dTodaySEXP, SEXP i_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type param(paramSEXP);
    Rcpp::traits::input_parameter< double >::type aToday(aTodaySEXP);
    Rcpp::traits::input_parameter< double >::type zToday(zTodaySEXP);
    Rcpp::traits::input_parameter< double >::type RToday(RTodaySEXP);
    Rcpp::traits::input_parameter< double >::type wToday(wTodaySEXP);
    Rcpp::traits::input_parameter< double >::type tauToday(tauTodaySEXP);
    Rcpp::traits::input_parameter< double >::type dToday(dTodaySEXP);
    Rcpp::traits::input_parameter< int >::type i_z(i_zSEXP);
    rcpp_result_gen = Rcpp::wrap(EGMconstrained(param, aToday, zToday, RToday, wToday, tauToday, dToday, i_z));
    return rcpp_result_gen;
END_RCPP
}
// HH_opt_EGM
List HH_opt_EGM(double beta, List param, NumericVector grid_a, NumericVector grid_z, NumericMatrix prob_z, double wToday, double RToday, double tauToday, double dToday, NumericMatrix pf_c_init, NumericMatrix pf_n_init, NumericMatrix pf_sav_init);
RcppExport SEXP _MNS2016_HH_opt_EGM(SEXP betaSEXP, SEXP paramSEXP, SEXP grid_aSEXP, SEXP grid_zSEXP, SEXP prob_zSEXP, SEXP wTodaySEXP, SEXP RTodaySEXP, SEXP tauTodaySEXP, SEXP dTodaySEXP, SEXP pf_c_initSEXP, SEXP pf_n_initSEXP, SEXP pf_sav_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_a(grid_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid_z(grid_zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prob_z(prob_zSEXP);
    Rcpp::traits::input_parameter< double >::type wToday(wTodaySEXP);
    Rcpp::traits::input_parameter< double >::type RToday(RTodaySEXP);
    Rcpp::traits::input_parameter< double >::type tauToday(tauTodaySEXP);
    Rcpp::traits::input_parameter< double >::type dToday(dTodaySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf_c_init(pf_c_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf_n_init(pf_n_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf_sav_init(pf_sav_initSEXP);
    rcpp_result_gen = Rcpp::wrap(HH_opt_EGM(beta, param, grid_a, grid_z, prob_z, wToday, RToday, tauToday, dToday, pf_c_init, pf_n_init, pf_sav_init));
    return rcpp_result_gen;
END_RCPP
}
// pchip
NumericVector pchip(NumericVector knot_x, NumericVector knot_y, NumericVector x);
RcppExport SEXP _MNS2016_pchip(SEXP knot_xSEXP, SEXP knot_ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type knot_x(knot_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type knot_y(knot_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pchip(knot_x, knot_y, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MNS2016_HH_dist", (DL_FUNC) &_MNS2016_HH_dist, 13},
    {"_MNS2016_EGMconstrained", (DL_FUNC) &_MNS2016_EGMconstrained, 8},
    {"_MNS2016_HH_opt_EGM", (DL_FUNC) &_MNS2016_HH_opt_EGM, 12},
    {"_MNS2016_pchip", (DL_FUNC) &_MNS2016_pchip, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MNS2016(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
